# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature/add-workflow" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install doxygen
      - name: Install Doxygen
        run: sudo apt-get install doxygen

      # Checkout the wiki. (https://github.com/actions/checkout)
      - uses: actions/checkout@v4
        with:
          repository: 'CleeveCoders/WiKi.wiki.git'
          path: 'wiki'
          ref: 'master'

      # Checkout live wiki.
      - uses: actions/checkout@v4
        with:
          repository: 'CleeveCoders/wiki.live.git'
          path: 'live'
          ref: 'main'
          token: ${{ secrets.PAT }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          doxygen .github/workflows/wiki.dox

      - name: Copy to live
        run: |
          cp -r ./html/* ./live/
          cd live
          git status
          git config --global user.email "bagshawwilliam@gmail.com"
          git config --global user.name "BillyBag2"
          git add .
          git commit -am "Commit by action"
          git push

      # Optional: Upload documentation as an artifact (can be downloaded from the Actions tab)
      - name: Archive Documentation
        uses: actions/upload-artifact@v4
        with:
          name: all
          path: .

